./TAPIN PM_MTNGH_CLIENT/PM_MTNGH_CLIENT@ORCL 2 1 /home/WBS_4.4/PM/GHANA_TAPIN_LTE_TEST_4.4_CODE/log/  TAPIN 45
#./ProcessTAP pm_rdm/pm_rdm@lt29 2 1 /home/roaming/roam/roam/PM/RAP_DEVELOPMENT/TAPIN/log/  TAPIN 45
